package com.example.mapper;

import com.example.entity.TblBook;
import com.example.entity.TblBookExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TblBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    long countByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int deleteByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int deleteByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int insert(TblBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int insertSelective(TblBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    List<TblBook> selectByExample(TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    TblBook selectByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int updateByExampleSelective(@Param("record") TblBook record, @Param("example") TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int updateByExample(@Param("record") TblBook record, @Param("example") TblBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int updateByPrimaryKeySelective(TblBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbg.generated Thu May 21 12:02:25 ICT 2020
     */
    int updateByPrimaryKey(TblBook record);
    
   
}