package com.example.mapper;

import com.example.entity.TblMember;
import com.example.entity.TblMemberExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TblMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    long countByExample(TblMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int deleteByExample(TblMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int deleteByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int insert(TblMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int insertSelective(TblMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    List<TblMember> selectByExample(TblMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    TblMember selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int updateByExampleSelective(@Param("record") TblMember record, @Param("example") TblMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int updateByExample(@Param("record") TblMember record, @Param("example") TblMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int updateByPrimaryKeySelective(TblMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    int updateByPrimaryKey(TblMember record);
    
    TblMember selectById(String memberId);
}