package com.example.mapper;

import com.example.entity.TblRental;
import com.example.entity.TblRentalExample;
import com.example.entity.TblRentalKey;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TblRentalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	long countByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int deleteByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int deleteByPrimaryKey(TblRentalKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int insert(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int insertSelective(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	List<TblRental> selectByExample(TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	TblRental selectByPrimaryKey(TblRentalKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int updateByExampleSelective(@Param("record") TblRental record, @Param("example") TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int updateByExample(@Param("record") TblRental record, @Param("example") TblRentalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int updateByPrimaryKeySelective(TblRental record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_rental
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	int updateByPrimaryKey(TblRental record);
	
	TblRental selectById(String memberId);
	TblRental henkyaku(String memberId);
}