package com.example.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TblMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public TblMemberExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("member_id like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("member_id not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameIsNull() {
            addCriterion("member_family_name is null");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameIsNotNull() {
            addCriterion("member_family_name is not null");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameEqualTo(String value) {
            addCriterion("member_family_name =", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameNotEqualTo(String value) {
            addCriterion("member_family_name <>", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameGreaterThan(String value) {
            addCriterion("member_family_name >", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameGreaterThanOrEqualTo(String value) {
            addCriterion("member_family_name >=", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameLessThan(String value) {
            addCriterion("member_family_name <", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameLessThanOrEqualTo(String value) {
            addCriterion("member_family_name <=", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameLike(String value) {
            addCriterion("member_family_name like", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameNotLike(String value) {
            addCriterion("member_family_name not like", value, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameIn(List<String> values) {
            addCriterion("member_family_name in", values, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameNotIn(List<String> values) {
            addCriterion("member_family_name not in", values, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameBetween(String value1, String value2) {
            addCriterion("member_family_name between", value1, value2, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameNotBetween(String value1, String value2) {
            addCriterion("member_family_name not between", value1, value2, "memberFamilyName");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaIsNull() {
            addCriterion("member_family_name_kana is null");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaIsNotNull() {
            addCriterion("member_family_name_kana is not null");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaEqualTo(String value) {
            addCriterion("member_family_name_kana =", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaNotEqualTo(String value) {
            addCriterion("member_family_name_kana <>", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaGreaterThan(String value) {
            addCriterion("member_family_name_kana >", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaGreaterThanOrEqualTo(String value) {
            addCriterion("member_family_name_kana >=", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaLessThan(String value) {
            addCriterion("member_family_name_kana <", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaLessThanOrEqualTo(String value) {
            addCriterion("member_family_name_kana <=", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaLike(String value) {
            addCriterion("member_family_name_kana like", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaNotLike(String value) {
            addCriterion("member_family_name_kana not like", value, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaIn(List<String> values) {
            addCriterion("member_family_name_kana in", values, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaNotIn(List<String> values) {
            addCriterion("member_family_name_kana not in", values, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaBetween(String value1, String value2) {
            addCriterion("member_family_name_kana between", value1, value2, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFamilyNameKanaNotBetween(String value1, String value2) {
            addCriterion("member_family_name_kana not between", value1, value2, "memberFamilyNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameIsNull() {
            addCriterion("member_first_name is null");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameIsNotNull() {
            addCriterion("member_first_name is not null");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameEqualTo(String value) {
            addCriterion("member_first_name =", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameNotEqualTo(String value) {
            addCriterion("member_first_name <>", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameGreaterThan(String value) {
            addCriterion("member_first_name >", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("member_first_name >=", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameLessThan(String value) {
            addCriterion("member_first_name <", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameLessThanOrEqualTo(String value) {
            addCriterion("member_first_name <=", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameLike(String value) {
            addCriterion("member_first_name like", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameNotLike(String value) {
            addCriterion("member_first_name not like", value, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameIn(List<String> values) {
            addCriterion("member_first_name in", values, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameNotIn(List<String> values) {
            addCriterion("member_first_name not in", values, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameBetween(String value1, String value2) {
            addCriterion("member_first_name between", value1, value2, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameNotBetween(String value1, String value2) {
            addCriterion("member_first_name not between", value1, value2, "memberFirstName");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaIsNull() {
            addCriterion("member_first_name_kana is null");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaIsNotNull() {
            addCriterion("member_first_name_kana is not null");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaEqualTo(String value) {
            addCriterion("member_first_name_kana =", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaNotEqualTo(String value) {
            addCriterion("member_first_name_kana <>", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaGreaterThan(String value) {
            addCriterion("member_first_name_kana >", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaGreaterThanOrEqualTo(String value) {
            addCriterion("member_first_name_kana >=", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaLessThan(String value) {
            addCriterion("member_first_name_kana <", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaLessThanOrEqualTo(String value) {
            addCriterion("member_first_name_kana <=", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaLike(String value) {
            addCriterion("member_first_name_kana like", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaNotLike(String value) {
            addCriterion("member_first_name_kana not like", value, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaIn(List<String> values) {
            addCriterion("member_first_name_kana in", values, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaNotIn(List<String> values) {
            addCriterion("member_first_name_kana not in", values, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaBetween(String value1, String value2) {
            addCriterion("member_first_name_kana between", value1, value2, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andMemberFirstNameKanaNotBetween(String value1, String value2) {
            addCriterion("member_first_name_kana not between", value1, value2, "memberFirstNameKana");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andBirthDayIsNull() {
            addCriterion("birth_day is null");
            return (Criteria) this;
        }

        public Criteria andBirthDayIsNotNull() {
            addCriterion("birth_day is not null");
            return (Criteria) this;
        }

        public Criteria andBirthDayEqualTo(Date value) {
            addCriterionForJDBCDate("birth_day =", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birth_day <>", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayGreaterThan(Date value) {
            addCriterionForJDBCDate("birth_day >", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birth_day >=", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayLessThan(Date value) {
            addCriterionForJDBCDate("birth_day <", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birth_day <=", value, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayIn(List<Date> values) {
            addCriterionForJDBCDate("birth_day in", values, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birth_day not in", values, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birth_day between", value1, value2, "birthDay");
            return (Criteria) this;
        }

        public Criteria andBirthDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birth_day not between", value1, value2, "birthDay");
            return (Criteria) this;
        }

        public Criteria andRegistIdIsNull() {
            addCriterion("regist_id is null");
            return (Criteria) this;
        }

        public Criteria andRegistIdIsNotNull() {
            addCriterion("regist_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegistIdEqualTo(String value) {
            addCriterion("regist_id =", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotEqualTo(String value) {
            addCriterion("regist_id <>", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThan(String value) {
            addCriterion("regist_id >", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThanOrEqualTo(String value) {
            addCriterion("regist_id >=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThan(String value) {
            addCriterion("regist_id <", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThanOrEqualTo(String value) {
            addCriterion("regist_id <=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLike(String value) {
            addCriterion("regist_id like", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotLike(String value) {
            addCriterion("regist_id not like", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdIn(List<String> values) {
            addCriterion("regist_id in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotIn(List<String> values) {
            addCriterion("regist_id not in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdBetween(String value1, String value2) {
            addCriterion("regist_id between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotBetween(String value1, String value2) {
            addCriterion("regist_id not between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNull() {
            addCriterion("regist_date is null");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNotNull() {
            addCriterion("regist_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegistDateEqualTo(Date value) {
            addCriterion("regist_date =", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotEqualTo(Date value) {
            addCriterion("regist_date <>", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThan(Date value) {
            addCriterion("regist_date >", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThanOrEqualTo(Date value) {
            addCriterion("regist_date >=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThan(Date value) {
            addCriterion("regist_date <", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThanOrEqualTo(Date value) {
            addCriterion("regist_date <=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateIn(List<Date> values) {
            addCriterion("regist_date in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotIn(List<Date> values) {
            addCriterion("regist_date not in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateBetween(Date value1, Date value2) {
            addCriterion("regist_date between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotBetween(Date value1, Date value2) {
            addCriterion("regist_date not between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("update_id like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("update_id not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_member
     *
     * @mbg.generated do_not_delete_during_merge Thu May 21 12:02:43 ICT 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_member
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}