package com.example.entity;

import java.util.Date;

public class TblMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.member_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.member_family_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String memberFamilyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.member_family_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String memberFamilyNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.member_first_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String memberFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.member_first_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String memberFirstNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.address
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.birth_day
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private Date birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.regist_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String registId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.regist_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.update_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.update_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.delete_flg
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.member_id
     *
     * @return the value of tbl_member.member_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.member_id
     *
     * @param memberId the value for tbl_member.member_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.member_family_name
     *
     * @return the value of tbl_member.member_family_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getMemberFamilyName() {
        return memberFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.member_family_name
     *
     * @param memberFamilyName the value for tbl_member.member_family_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setMemberFamilyName(String memberFamilyName) {
        this.memberFamilyName = memberFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.member_family_name_kana
     *
     * @return the value of tbl_member.member_family_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getMemberFamilyNameKana() {
        return memberFamilyNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.member_family_name_kana
     *
     * @param memberFamilyNameKana the value for tbl_member.member_family_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setMemberFamilyNameKana(String memberFamilyNameKana) {
        this.memberFamilyNameKana = memberFamilyNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.member_first_name
     *
     * @return the value of tbl_member.member_first_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getMemberFirstName() {
        return memberFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.member_first_name
     *
     * @param memberFirstName the value for tbl_member.member_first_name
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setMemberFirstName(String memberFirstName) {
        this.memberFirstName = memberFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.member_first_name_kana
     *
     * @return the value of tbl_member.member_first_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getMemberFirstNameKana() {
        return memberFirstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.member_first_name_kana
     *
     * @param memberFirstNameKana the value for tbl_member.member_first_name_kana
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setMemberFirstNameKana(String memberFirstNameKana) {
        this.memberFirstNameKana = memberFirstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.address
     *
     * @return the value of tbl_member.address
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.address
     *
     * @param address the value for tbl_member.address
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.birth_day
     *
     * @return the value of tbl_member.birth_day
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.birth_day
     *
     * @param birthDay the value for tbl_member.birth_day
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.regist_id
     *
     * @return the value of tbl_member.regist_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getRegistId() {
        return registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.regist_id
     *
     * @param registId the value for tbl_member.regist_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setRegistId(String registId) {
        this.registId = registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.regist_date
     *
     * @return the value of tbl_member.regist_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.regist_date
     *
     * @param registDate the value for tbl_member.regist_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.update_id
     *
     * @return the value of tbl_member.update_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.update_id
     *
     * @param updateId the value for tbl_member.update_id
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.update_date
     *
     * @return the value of tbl_member.update_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.update_date
     *
     * @param updateDate the value for tbl_member.update_date
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.delete_flg
     *
     * @return the value of tbl_member.delete_flg
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.delete_flg
     *
     * @param deleteFlg the value for tbl_member.delete_flg
     *
     * @mbg.generated Thu May 21 12:02:43 ICT 2020
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}