package com.example.entity;

import java.util.Date;

public class TblRentalKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_rental.member_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	private String memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_rental.book_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	private String bookId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_rental.rental_date
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	private Date rentalDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_rental.member_id
	 * @return  the value of tbl_rental.member_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_rental.member_id
	 * @param memberId  the value for tbl_rental.member_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_rental.book_id
	 * @return  the value of tbl_rental.book_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public String getBookId() {
		return bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_rental.book_id
	 * @param bookId  the value for tbl_rental.book_id
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_rental.rental_date
	 * @return  the value of tbl_rental.rental_date
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public Date getRentalDate() {
		return rentalDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_rental.rental_date
	 * @param rentalDate  the value for tbl_rental.rental_date
	 * @mbg.generated  Tue Jun 23 13:35:33 JST 2020
	 */
	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}
}